
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /tmp 
    server: 172.17.0.2 
  persistentVolumeReclaimPolicy: Retain







apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
capacity:
storage: 500Gi # This is the maximum size of the DB2 persistent volume
nfs: # For illustrative purposes, this is a persistent volume defined on NFS storage.
server: 192.168.22.1
path: /mnt/db2wh # For illustrative purposes, this must be a path exclusive for DB2 use.
accessModes:
- ReadWriteMany # This must be defined to be correctly claimed.
persistentVolumeReclaimPolicy: Retain
storageClassName: sd-sc



apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfsshare
    server: 172.16.2.10
  persistentVolumeReclaimPolicy: Retain
