apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: bastion.dct-ocp-01.testad.com:8443/mirror/oc-mirror-metadata
    skipTLS: false
mirror:
  operators:
      - catalog: registry.redhat.io/redhat/certified-operator-index:v4.15
        packages:
         - name: dynatrace-operator
           channels: 
             - name: alpha
               minVersion: '1.1.0'
               maxVersion: '1.1.0'
      - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.15
        packages:
          - name: ocs-operator
            channels:
              - name: stable-4.15
                minVersion: '4.15.2-rhodf'
                maxVersion: '4.15.2-rhodf'

              - name: stable-4.15
                minVersion: '4.15.2-rhodf'
                maxVersion: '4.15.2-rhodf'
          - name: odf-operator
            channels:
              - name: stable-4.15
                minVersion: '4.15.2-rhodf'
                maxVersion: '4.15.2-rhodf'
          - name: mcg-operator
            channels:
              - name: stable-4.15
                minVersion: '4.15.2-rhodf'
                maxVersion: '4.15.2-rhodf'
          - name: odf-csi-addons-operator
            channels:
              - name: stable-4.15
                minVersion: '4.15.2-rhodf'
                maxVersion: '4.15.2-rhodf'
          - name: odr-cluster-operator
            channels:
              - name: stable-4.15
                minVersion: '4.15.2-rhodf'
                maxVersion: '4.15.2-rhodf'
          - name: odr-hub-operator
            channels:
              - name: stable-4.15
                minVersion: '4.15.2-rhodf'
                maxVersion: '4.15.2-rhodf'

          - name: advanced-cluster-management
            channels:
              - name: release-2.10 
                minVersion: 'v2.10.3'
                maxVersion: 'v2.10.3'
          - name: multicluster-engine
            channels:
              - name: stable-2.5 
                minVersion: 'v2.5.3'
                maxVersion: 'v2.5.3'
          - name: rhacs-operator
            channels:
              - name: latest
                minVersion: 'v3.74.9'
                maxVersion: 'v3.74.9'
          - name: loki-operator
            channels:
              - name: stable-5.9 
              - name: stable
                minVersion: 'v5.9.2'
                maxVersion: 'v5.9.2'
          - name: cluster-logging
            channels:
              - name: stable-5.9
              - name: stable
                minVersion: 'v5.9.2'
                maxVersion: 'v5.9.2'
          - name: compliance-operator
            channels:
              - name: stable
                minVersion: 'v1.4.1'
                maxVersion: 'v1.4.1'
          - name: metallb-operator
            channels:
              - name: stable 
                minVersion: 'v4.15.0-202405150336'
                maxVersion: 'v4.15.0-202405150336'
          - name: openshift-gitops-operator
            channels:
              - name: latest
                minVersion: 'v1.12.2'
                maxVersion: 'v1.12.2'
          - name: cincinnati-operator
            channels:
              - name: v1
                minVersion: 'v5.0.2'
                maxVersion: 'v5.0.2'
          - name: redhat-oadp-operator
            defaultChannel: stable-1.3
            channels:
              - name: stable
                name: stable-1.3
              - name: stable-1.1
                minVersion: 'v1.1.8'
                maxVersion: 'v1.1.8'
  additionalimages:
     - name: registry.redhat.io/ubi8/ubi:latest
     - name: registry.redhat.io/rhel8/support-tools:latest
     - name: quay.io/openshift/origin-must-gather:latest

